##image: "docker-snapshot.nexus.kesselrun.us/library/node:15.14.0"
image: "node:15"

stages:
  - build
  - test
  - deploy

# These folders are cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    # Default cache directory from https://classic.yarnpkg.com/en/docs/install-ci/#gitlab.
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

yarn:install:
  stage: build
  script:
    - rm -rf node_modules/
    - yarn add fs path
    # Install via yarn with frozen-lockfile to allow reproducible dependencies and check-files option to check if the node_modules cache is valid.
    - yarn install --frozen-lockfile --check-files --non-interactive
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

# test:unit:
#   stage: test
#   needs: ["yarn:install"]
#   script:
#     - yarn test:unit
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_MERGE_REQUEST_ID

# test:gatsby:
#   stage: test
#   needs: ["yarn:install"]
#   script:
#     - ./node_modules/.bin/gatsby info
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     - if: $CI_MERGE_REQUEST_ID

pages:
  stage: deploy
  needs: 
    - yarn:install
    # - test:unit
    # - test:gatsby
  script:
    - yarn add fs path
    - if [ -d ".git/modules/dev-support-templates" ]; then rm -rf .git/modules/dev-support-templates; fi 
    - git submodule add https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.kesselrun.us/kr/adcp/integration/dev-support-templates.git
    - git submodule add https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.kesselrun.us/kr/adcp/integration/dev-support-service-desk.git
    - git submodule update --init --recursive
    - ls .git/modules
    - rm dev-support-service-desk/.gitlab/issue_templates/*.md
    - cp dev-support-templates/templates/*.md dev-support-service-desk/.gitlab/issue_templates/
    - pushd .
    - cd dev-support-service-desk; ls -la; ls -la .git
    - ts=$(date +%F_%T);
    - |
      if [[ `git status --porcelain` ]]; then
        echo "There are template changes."
        
        ## git config steps below are required
        git config --global user.email "$GITLAB_USER_EMAIL"
        git config --global user.name "$GITLAB_USER_NAME"

        git branch -M main
        git config --list
        git add -A
        git status; git commit -m "Copy templates - $ts";

        ## This does not work!!
        # git push -vuf https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.kesselrun.us/kr/adcp/integration/dev-support-service-desk.git main

        ## This is using SD token named sd-maintainer-rw-access-token-1 and it works
        git push -vvv -uf https://gitlab-ci-token:nrfTAkz-z8UpebxopsNY@gitlab.kesselrun.us/kr/adcp/integration/dev-support-service-desk.git main

        echo "Template changes are pushed."
      else
        echo "No template changes."
      fi

    - popd

    - npm run prebuild
    - ./node_modules/.bin/gatsby clean
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

